export const topicOptions = [
  { label: 'HTML', value: 'html' },
  { label: 'CSS', value: 'css' },
  { label: 'JavaScript (ES6+)', value: 'javascript-es6' },
  { label: 'TypeScript', value: 'typescript' },
  { label: 'Vue 2', value: 'vue2' },
  { label: 'Vue 3', value: 'vue3' },
  { label: 'React', value: 'react' },
  { label: 'React Native', value: 'react-native' },
  { label: 'Next.js', value: 'nextjs' },
  { label: 'Nuxt 2', value: 'nuxt2' },
  { label: 'Nuxt 3', value: 'nuxt3' },
  { label: 'Angular 2+', value: 'angular' },
  { label: 'Svelte', value: 'svelte' },
  { label: 'SvelteKit', value: 'sveltekit' },
  { label: 'Node.js', value: 'nodejs' },
  { label: 'Express.js', value: 'expressjs' },
  { label: 'NestJS', value: 'nestjs' },
  { label: 'Deno', value: 'deno' },
  { label: 'Flutter', value: 'flutter' },
  { label: 'Dart', value: 'dart' },
  { label: 'Firebase', value: 'firebase' },
  { label: 'MongoDB', value: 'mongodb' },
  { label: 'MySQL', value: 'mysql' },
  { label: 'PostgreSQL', value: 'postgresql' },
  { label: 'GraphQL', value: 'graphql' },
  { label: 'REST API', value: 'rest-api' },
  { label: 'JWT Authentication', value: 'jwt-auth' },
  { label: 'OAuth 2.0', value: 'oauth2' },
  { label: 'Git & GitHub', value: 'git-github' },
  { label: 'Docker', value: 'docker' },
  { label: 'CI/CD Pipelines', value: 'ci-cd' },
  { label: 'Web Security (XSS, CSRF)', value: 'web-security' },
  { label: 'Tailwind CSS', value: 'tailwindcss' },
  { label: 'Bootstrap 5', value: 'bootstrap5' },
  { label: 'Jest Testing', value: 'jest' },
  { label: 'Vitest', value: 'vitest' },
  { label: 'Webpack', value: 'webpack' },
  { label: 'Vite', value: 'vite' },
  { label: 'Babel', value: 'babel' },
  { label: 'PWA (Progressive Web Apps)', value: 'pwa' },
  { label: 'Software Architecture', value: 'software-architecture' },
  { label: 'Design Patterns', value: 'design-patterns' },
  { label: 'Algorithms & Data Structures', value: 'algorithms-data-structures' },
]

export const countOption = [
  { label: 5, value: 5 },
  { label: 10, value: 10 },
  { label: 15, value: 15 },
  { label: 20, value: 20 },
]

export const DifficultyOptions = [
  {
    label: 'Easy',
    value: 'easy',
  },
  {
    label: 'Medium',
    value: 'medium',
  },
  {
    label: 'Hard',
    value: 'hard',
  },
]
